import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

const svelteOptions = {
	preprocess: sveltePreprocess(),
	compilerOptions: {
		dev: !prod,
		css: "injected"  // 使用注入式 CSS 以提高性能
	}
};

// esbuild 配置
const buildOptions = {
	plugins: [
		esbuildSvelte(svelteOptions)
	],
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
		'import.meta.env.DEV': (!prod).toString(),
		'import.meta.env.PROD': prod.toString(),
	},
	// 添加性能优化选项
	metafile: true,  // 生成构建元数据，用于分析
	legalComments: "none",  // 移除注释以减小文件体积
	loader: {
		'.svelte': 'text',  // 显式指定 Svelte 文件的加载器
	}
};

try {
	const context = await esbuild.context(buildOptions);

	if (prod) {
		// 生产环境构建
		const result = await context.rebuild();
		// 如果需要，可以分析构建结果
		if (result.metafile) {
			const analysis = await esbuild.analyzeMetafile(result.metafile);
			console.log(analysis);
		}
		process.exit(0);
	} else {
		// 开发环境监听
		await context.watch();
		console.log('Watching for changes...');
	}
} catch (err) {
	console.error('Build failed:', err);
	process.exit(1);
}
